### ISSUE TITLE
Add note on "comment considered" issue tag

### ISSUE THREAD

**Issue by chris-wood** [ietf-gitwg/using-github#13]
Filing after discussion with Paul Hoffman. The main idea is that this gives folks a way to convey to readers that an issue or message was read by an editor, chair, etc. In contrast, one cannot distinguish a lack of response between an editor or chair having not read it or having read it and choosing not to act on it.

**Comment by martinthomson** [comment]
(Assuming this refers to labels and not tags...)

I don't think that this sort of signal is useful.  If someone is lacking feedback, things can be taken to mailing lists.

It is often useful for bigger projects to have labels for triaging issues, which might as a side-effect indicate that things have been read, but that isn't their primary purpose.  For instance, in QUIC we have a design/editorial distinction that is conveyed with labels, and also a label for which document the issue applies to.

The most valuable label I've seen recently is a 'has-consensus' label, which QUIC has attached to issues where the working group has explicitly considered the issue and reached a conclusion.  I think that's been useful, but it's probably less useful from the outside because most of those issues are closed at about the same time the label goes on.

**Comment by chris-wood** [comment]
> If someone is lacking feedback, things can be taken to mailing lists.

The complaint that led to this issue was that taking it to the list might turn up nothing. 

In any case, an issue that's not yet been triaged (and labelled) is indistinguishable from a message on a list that received zero responses. Adding a label to indicate that something's been considered might only then be useful if there's no other appropriate label. In QUIC's case, triage requires slapping on a design or editorial label (or some other thing), for example. I imagine there might be groups where that sort of triage classification isn't a thing, and for them, this might be useful. 

As with all of this stuff, YMMV. I suggest we not add anything here absent a concrete PR.

**Comment by chris-wood** [comment]
Closing since there's been no PR!
