### ISSUE TITLE
Need more discussion of turning off features

### ISSUE THREAD

**Issue by paulehoffman** [ietf-gitwg/using-github#20]
Section 3.1 talks about turning off GitHub features not being used by the WG, but it doesn't say how to do that in the UI. I ask this because I cannot see a way to prevent issues or PRs just by wandering through the GUI.

**Comment by martinthomson** [comment]
This isn't something that I'd want to publish.  The way that features are configured is too tightly coupled to UX decisions that GitHub might remake and any point.

In fact, I might prefer not to include the offending text at all.  Disabling features can be a useful way to slim down the options presented to users (which can help new users), but it can also be fairly hostile to new contributors.  For instance, if the working group disables issues because they aren't using them, it sounds reasonable, but new contributors might then be dissuaded from opening a genuine issue.  Working groups might be better served by informally letting contributors know how to best provide their input.

**Comment by paulehoffman** [comment]
I'm happy with either the current text plus "At the time this is written, to turn of $x do $y" or removing the suggestion.
