### ISSUE TITLE
Can one prevent comments on PRs?

### ISSUE THREAD

**Issue by paulehoffman** [ietf-gitwg/using-github#23]
Section 4.2.1 explains why comments in PRs can make WG discussion difficult. Can one prevent comments on PRs? If so, the steps for how to do that should be added to this section.

**Comment by martinthomson** [comment]
The problem here is that comments on PRs are invaluable for resolving editorial issues.  For instance, almost every PR in QUIC has comments about spelling and grammar.  There are also minor comments (this says X but it now needs to consider Y; you deleted this but it is important).  And these are all hugely valuable forms of feedback, without which I don't think that pull requests would be useful.

The problem is when this spirals out of control.  A major discussion of an issue can spawn from one of these discussions.  Learning how to identify that line is hard.  I think that the best we can do is add a caution.

**Comment by paulehoffman** [comment]
"You might be able to, but it is not advised" seems reasonable.
